apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-deployment
spec:
  selector:
    matchLabels:
      app: speedtest-app
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: speedtest-app
    spec:
      containers:
      - name: speedtest-container
        image: russrace/speedtest:latest
        imagePullPolicy:  IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-svc
spec:
  type: LoadBalancer
  selector:
    app: speedtest-app
  ports:
  - protocol: TCP
    port: 80  # the port that will be exposed from the load balancer
    targetPort: 8080 # the applications container port