apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
      nodePort: 30001
  selector:
    app: influxdb
  sessionAffinity: None
  type: LoadBalancer