apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrony-deployment
spec:
  selector:
    matchLabels:
      app: chrony-app
  replicas: 4 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: chrony-app
    spec:
      containers:
      - name: chrony-container
        image: russrace/chrony:1.0.2
        imagePullPolicy:  IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 123
---
apiVersion: v1
kind: Service
metadata:
  name: chrony-svc
spec:
  type: LoadBalancer
  selector:
    app: chrony-app
  ports:
  - protocol: UDP
    port: 123  # the port that will be exposed from the load balancer
    targetPort: 123 # the applications container port