apiVersion: v1
kind: Service
metadata:
  name: telegraf
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 8125
    protocol: UDP
    targetPort: 8125
  selector:
    app: telegraf
  sessionAffinity: None
  type: LoadBalancer